language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
env:
  global:
    - SOUTH_TESTS_MIGRATE=1
  matrix:
    - TOX_ENV=py26-dj14-sqlite
    - TOX_ENV=py26-dj14-mysql
    - TOX_ENV=py26-dj14-postgres
    - TOX_ENV=py26-dj15-sqlite
    - TOX_ENV=py26-dj15-mysql
    - TOX_ENV=py26-dj15-postgres
    - TOX_ENV=py27-dj14-sqlite
    - TOX_ENV=py27-dj14-mysql
    - TOX_ENV=py27-dj14-postgres
    - TOX_ENV=py27-dj15-sqlite
    - TOX_ENV=py27-dj15-mysql
    - TOX_ENV=py27-dj15-postgres
    - TOX_ENV=py27-dj16-sqlite
    - TOX_ENV=py27-dj16-mysql
    - TOX_ENV=py27-dj16-postgres
    - TOX_ENV=javascript
    - TOX_ENV=py26-dj14-contrib
    - TOX_ENV=py26-dj15-contrib
    - TOX_ENV=py26-dj16-contrib
    - TOX_ENV=py27-dj14-contrib
    - TOX_ENV=py27-dj15-contrib
    - TOX_ENV=py27-dj16-contrib
install:
  - pip install --upgrade pip
  - pip install tox
before_script:
  - psql -c 'create database widgy;' -U postgres
  - mysql -e 'create database widgy;'
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
